CM-326: Fixed labels
openimis/openimis-fe-payroll_js pull request #10
Opened 2023-09-27 15:41 UTC by dborowiecki

Some of the labels were not included in translations which resulted in display of unintuitive keys. 

There is still issue with handling error output from backend but it's not adressed in scope of this PR.

2023-09-28 06:37 UTC, olewandowski1 commented on src/translations/en.json
> +
Redundant empty line.

2023-09-28 06:37 UTC, olewandowski1 commented on src/translations/en.json
> +
Redundant empty line.

2023-09-28 06:40 UTC, olewandowski1 requested changes
Overall, there are just two minor comments. I noticed that you're passing {name} as a parameter to the mutation label. Please double-check if the payroll name is restricted in terms of length. If a user creates an exceptionally long name and the mutation label exceeds 255 characters, you won't be able to create or delete it (similar to the issue with individuals).

2023-12-11 15:04 UTC, delcroip approved these changes

2023-12-11 15:05 UTC, delcroip commented on src/translations/en.json
> +
@dborowiecki  should I merge anway ?

2024-04-24 08:58 UTC, dborowiecki commented
Closing as stale.

2024-04-24 08:58 UTC, closed without merging